### ISSUE TITLE
Nodebb not connecting with DB on v1.18.5

### ISSUE THREAD

**Issue by fais3000** [rez0n/docker-nodebb#337]
On upgrading image from 1.18.1 to v1.18.5, nodebb service is chrasing with following error.

```
2021-11-28T10:48:21.789Z [4567/11] - error: TypeError [ERR_INVALID_URL]: Invalid URL: mongodb://mongodb:27017:"27017"

    at onParseError (internal/url.js:258:9)

    at new URL (internal/url.js:334:5)

    at new HostAddress (/usr/src/app/node_modules/mongodb/lib/utils.js:1041:36)

    at fromString (/usr/src/app/node_modules/mongodb/lib/utils.js:1085:16)

    at Array.map (<anonymous>)

    at Object.parseOptions (/usr/src/app/node_modules/mongodb/lib/connection_string.js:213:45)

    at new MongoClient (/usr/src/app/node_modules/mongodb/lib/mongo_client.js:62:46)

    at Function.connect (/usr/src/app/node_modules/mongodb/lib/mongo_client.js:184:33)

    at Object.connection.connect (/usr/src/app/src/database/mongo/connection.js:61:27)

    at mongoModule.init (/usr/src/app/src/database/mongo.js:63:28)
```

Tried with mongodb 4.4 and 5. Reverting nodebb image back starts to work again. Have there been any changes to the way configs are done with the new version?

**Comment by fais3000** [comment]
Seems to be linked with strictness around MongoDB's connection string in the new version. https://docs.mongodb.com/manual/reference/connection-string/
